### ISSUE TITLE
support for ros2_control when?

### ISSUE THREAD

**Issue by ichumuh** [Multiverse-Framework/Multiverse#35]

**Comment by HoangGiang93** [comment]
next week :)

**Comment by HoangGiang93** [comment]
It's done. Try that out with this command line:
`multiverse_launch multiverse/resources/muv/ur5e_ros2_control.muv`

[Video.webm](https://github.com/user-attachments/assets/af653485-2ec7-4d30-8c3a-4a02cd9df016)

**Comment by ichumuh** [comment]
do forward velocity controllers also work?

**Comment by HoangGiang93** [comment]
It should work, just change the yaml file in the config and change joint_trajectory_controller to whatever controller you want. Let me know if something breaks.

**Comment by ichumuh** [comment]
:magic_wand:
