### ISSUE TITLE
Add support for showing and getting bounding boxes.

### ISSUE THREAD

**Issue by AbdelrhmanBassiouny** [Multiverse-Framework/Multiverse#40]
Mujoco has already a feature in its viewer that shows the bounding boxes of objects called "Body Tree" under "Rendering".
![image](https://github.com/user-attachments/assets/1f59cb75-f361-40c6-9e02-5a67a3cd1fd7)

**Comment by HoangGiang93** [comment]
https://github.com/user-attachments/assets/20977b45-a494-4bd3-a1fa-6bbfdc1cf4b6

It's finished, you can test it by command:

```
multiverse_launch path/to/empty_with_rviz.muv
```

Then run this [test](https://github.com/Multiverse-Framework/Multiverse/blob/main/multiverse/modules/multiverse_connectors/src/multiverse_client_py/tests/test_mulitverse_client_py.py#L1019-L1036).

The input is 1 or 2 arguments, the first one is the name of the body, the second one is optional, either `ẁith_children` or not specified.
The response will be a list of vector. Each vector contains 6 number for each geom of the body. The first 3 are the position of the bounding box in body frame, the last 3 are the size of the bounding box.
You can use rviz to visualize the bounding boxes, note that it's not the visualization of the bounding boxes as the result of the API. That will be done later using visualization marker.
